name: 101.yaml Shell commands testing
on:
  repository_dispatch:
    types: [echoing]
jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello-himanshuDevopsGuy"
      - name: multi-line script
        run: |
                 echo "Hello-there"
                 echo "hello-all"




