name: Environment variables test
on: 
  push:
    branches:
      - "104"
  pull_request:
    types:
      - "opened"
jobs:
 job-1 :
    runs-on:  ubuntu-latest
    env:
      VAR_1: "Available within the job 1"
    steps:
      - name:  Environment varibale for step 1
        env:
          VAR_2: Avaialable for step1 only
        run: |
          echo "VAR_1: ${VAR_1}"
          echo "VAR_2: ${VAR_2}"
      - name:  Environment varaible for step 2
        env:
          VAR_3 : Available for step 3
        run: |
          echo "VAR_1: ${VAR_1}"
          echo "VAR_2: ${VAR_2}"
          echo "VAR_3: ${VAR_3}"

  job-2 :
    needs: job-1
    runs-on: ubuntu-latest
    env:
      VAR_1: Avaialable for job 2
    steps:
      - name: Echoing all the variables
        run: |
          echo "VAR_1: ${VAR_1}"
          echo "VAR_2: ${VAR_2}"
          echo "VAR_3: ${VAR_3}"
